[project]
name = "sbc-sc"
requirements = []
costs_version = 1
[contracts.abc-token]
path = "contracts/abc-token.clar"
depends_on = ["sip010-ft-trait"]

[contracts.sbc-core]
path = "contracts/sbc-core.clar"
depends_on = []

[contracts.sbc-token]
path = "contracts/sbc-token.clar"
depends_on = ["sip010-ft-trait"]

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"
depends_on = []

[contracts.tsbc-token]
path = "contracts/tsbc-token.clar"
depends_on = ["sip010-ft-trait"]
